version: '3.4'

networks:
  dev:
    driver: 
        bridge

services:
  signalgrapher.api:
    image: ${DOCKER_REGISTRY-}signalgrapherapi
    build:
      context: .
      dockerfile: SignalGrapher.API/Dockerfile
    environment:
        - ConnectionStrings__DefaultConnection=User ID =postgres;Password=1234;Server=postgres_db;Port=5432;Database=signal-db;Pooling=true;
    depends_on:
      - postgres_db 
    networks:
          - dev

  postgres_db:
    container_name: signals-db
    image: postgres:latest
    environment:
        POSTGRES_PASSWORD: 1234
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
    networks:
        - dev

  client:
    container_name: client
    build:
      context: ./SignalGrapher.ClientApp
      dockerfile: Dockerfile
    networks:
          - dev
  
  proxy: 
    image: nginx:mainline
    depends_on:
          -  signalgrapher.api
    networks:
          - dev