// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SignalGrapher.Infrastructure.Persistence;

#nullable disable

namespace SignalGrapher.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SignalGrapher.Domain.SinusoidalSignals.SinusoidalSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amplitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodValue")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PlotImage")
                        .IsRequired()
                        .HasMaxLength(5242880)
                        .HasColumnType("bytea");

                    b.Property<double>("SamplingFrequency")
                        .HasColumnType("double precision");

                    b.Property<double>("SignalFrequency")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("SinusoidalSignals");
                });
#pragma warning restore 612, 618
        }
    }
}
